<?php

namespace App\Clients;

use GuzzleHttp\Client;

class ScopusSearchClient
{
    protected $client;

    public $queries = [
        'food' => 'TITLE-ABS-KEY ( ( {land tenure rights}  OR  ( smallholder  AND  ( farm  OR  forestry  OR  pastoral  OR  agriculture  OR  fishery  OR  {food producer}  OR  {food producers} ) )  OR  malnourish*  OR  malnutrition  OR  undernourish*  OR  {undernutrition}  OR  {agricultural production}  OR  {agricultural productivity}  OR  {agricultural practices}  OR  {agricultural management}  OR  {food production}  OR  {food productivity}  OR  {food security}  OR  {food insecurity}  OR  {land right}  OR  {land rights}  OR  {land reform}  OR  {land reforms}  OR  {resilient agricultural practices}  OR  ( agriculture  AND  potassium )  OR  fertili?er  OR  {food nutrition improvement}  OR  {hidden hunger}  OR  {genetically modified food}  OR  ( gmo  AND  food )  OR  {agroforestry practices}  OR  {agroforestry management}  OR  {agricultural innovation}  OR  ( {food security}  AND  {genetic diversity} )  OR  ( {food market}  AND  ( restriction  OR  tariff  OR  access  OR  {north south divide}  OR  {development governance} ) )  OR  {food governance}  OR  {food supply chain}  OR  {food value chain}  OR  {food commodity market}  AND NOT  {disease} ) )',

        'health' => 'TITLE-ABS-KEY ( ( ( human AND ( health* OR disease* OR illness* OR medicine* OR mortality ) ) OR {battered child syndrome} OR {cardiovascular disease} OR {cardiovascular diseases} OR {chagas} OR {child abuse} OR {child neglect} OR {child well-being index} OR {youth well-being index} OR {child wellbeing index} OR {youth wellbeing index} OR {water-borne disease} OR {water-borne diseases} OR {water borne disease} OR {water borne diseases} OR {tropical disease} OR {tropical diseases} OR {chronic respiratory disease} OR {chronic respiratory diseases} OR {infectious disease} OR {infectious diseases} OR {sexually-transmitted disease} OR {sexually transmitted disease} OR {sexually-transmitted diseases} OR {sexually transmitted diseases} OR {communicable disease} OR {communicable diseases} OR aids OR hiv OR {human immunodeficiency virus} OR tuberculosis OR malaria OR hepatitis OR polio* OR vaccin* OR cancer* OR diabet* OR {maternal mortality} OR {child mortality} OR {childbirth complications} OR {neonatal mortality} OR {neo-natal mortality} OR {premature mortality} OR {infant mortality} OR {quality adjusted life year} OR {maternal health} OR {preventable death} OR {preventable deaths} OR {tobacco control} OR {substance abuse} OR {drug abuse} OR {tobacco use} OR {alcohol use} OR {substance addiction} OR {drug addiction} OR {tobacco addiction} OR alcoholism OR suicid* OR {postnatal depression} OR {post-natal depression} OR {zika virus} OR dengue OR schistosomiasis OR {sleeping sickness} OR ebola OR {mental health} OR {mental disorder} OR {mental illness} OR {mental illnesses} OR {measles} OR {neglected disease} OR {neglected diseases} OR diarrhea OR diarrhoea OR cholera OR dysentery OR {typhoid fever} OR {traffic accident} OR {traffic accidents} OR {healthy lifestyle} OR {life expectancy} OR {life expectancies} OR {health policy} OR ( {health system} AND ( access OR accessible ) ) OR {health risk} OR {health risks} OR {inclusive health} OR obesity OR {social determinants of health} OR {psychological harm} OR {psychological wellbeing} OR {psychological well-being} OR {psychological well being} OR {public health} ) )',

        'disaster' => 'TITLE-ABS-KEY((disaster AND management) OR (disaster AND mitigation) OR (disaster AND risk AND assessment) OR (disaster AND risk AND management) OR (disaster AND risk AND reduction) OR (hazard AND mapping) OR {hazard modelling} OR {susceptibility mapping} OR {vulnerability mapping} OR {coping capacity} OR (community AND resilience) OR preparedness OR {early warning system} OR (geological AND hazard) OR (volcan* AND hazard) OR (tectonic AND hazard) OR (meteorological AND hazard) OR (hydrological AND hazard) OR (hydrometeorological AND hazard) OR earthquake OR (eruption AND disaster) OR landslide OR flood OR tsunami OR ((plague OR pandemic OR endemic OR epidemic) AND disaster) OR (drought AND disaster) OR cyclone OR {storm surge})',

        'energy' => 'TITLE-ABS-KEY ( ( {energy efficiency}  OR  {energy consumption}  OR  {energy transition}  OR  {clean energy technology}  OR  {energy equity}  OR  {energy justice}  OR  {energy poverty}  OR  {energy policy}  OR  renewable*  OR  {2000 Watt society}  OR  {smart micro-grid}  OR  {smart grid}  OR  {smart microgrid}  OR  {smart micro-grids}  OR  {smart grids}  OR  {smart microgrids}  OR  {smart meter}  OR  {smart meters}  OR  {affordable electricity}  OR  {electricity consumption}  OR  {reliable electricity}  OR  {clean fuel}  OR  {clean cooking fuel}  OR  {fuel poverty}  OR  energiewende  OR  {life-cycle assessment}  OR  {life cycle assessment}  OR  {life-cycle assessments}  OR  {life cycle assessments}  OR  ( {photochemistry}  AND  {renewable energy} )  OR  photovoltaic  OR  {photocatalytic water splitting}  OR  {hydrogen production}  OR  {water splitting}  OR  {lithium-ion batteries}  OR  {lithium-ion battery}  OR  {heat network}  OR  {district heat}  OR  {district heating}  OR  {residential energy consumption}  OR  {domestic energy consumption}  OR  {energy security}  OR  {rural electrification}  OR  {energy ladder}  OR  {energy access}  OR  {energy conservation}  OR  {low-carbon society}  OR  {hybrid renewable energy system}  OR  {hybrid renewable energy systems}  OR  {fuel switching}  OR  ( {foreign development aid}  AND  {renewable energy} )  OR  {energy governance}  OR  ( {official development assistance}  AND  {electricity} )  OR  ( {energy development}  AND  {developing countries} ) )  AND NOT  ( {wireless sensor network}  OR  {wireless sensor networks} ) )',

        'climate' => "TITLE-ABS-KEY ( ( {climate action}  OR  {climate adaptation}  OR  {climate change}  OR  {climate capitalism}  OR  ipcc  OR  {climate effect}  OR  {climate equity}  OR  {climate feedback}  OR  {climate finance}  OR  {climate change financing}  OR  {climate forcing}  OR  {climate governance}  OR  {climate impact}  OR  {climate investment}  OR  {climate justice}  OR  {climate mitigation}  OR  {climate model}  OR  {climate models}  OR  {climate modeling}  OR  {climate modelling}  OR  {climate policy}  OR  {climate policies}  OR  {climate risk}  OR  {climate risks}  OR  {climate services}  OR  {climate service}  OR  {climate prediction}  OR  {climate predictions}  OR  {climate signal}  OR  {climate signals}  OR  {climate tipping point}  OR  {climate variation}  OR  {climate variations}  OR  ecoclimatology  OR  eco-climatology  OR  {Green Climate Fund}  OR  {regional climate}  OR  {regional climates}  OR  {urban climate}  OR  {urban climates}  OR  ( climate  AND  ( {adaptive management}  OR  awareness  OR  bioeconomy  OR  carbon  OR  {decision-making}  OR  {disaster risk reduction}  OR  {environmental education}  OR  {sustainable development education}  OR  {energy conservation}  OR  emission*  OR  extreme  OR  {food chain}  OR  {food chains}  OR  framework  OR  hazard*  OR  island*  OR  {land use}  OR  megacit*  OR  consumption  OR  production  OR  {small island developing states}  OR  anthropocene  OR  atmospher*  OR  {clean development mechanism}  OR  {glacier retreat}  OR  warming  OR  greenhouse  OR  {ice-ocean interaction}  OR  {ice-ocean interactions}  OR  {nitrogen cycle}  OR  {nitrogen cycles}  OR  {ocean acidification}  OR  {radiative forcing}  OR  {sea ice}  OR  {sea level}  OR  {sea levels}  OR  {thermal expansion}  OR  unfccc  OR  ozone ) ) )  AND NOT  ( {drug}  OR  {geomorphology} ) )",

        'gender' => "TITLE-ABS-KEY ( ( {gender inequality} OR {gender equality} OR {employment equity} OR {gender wage gap} OR {female labor force participation} OR {female labour force participation} OR {women labor force participation} OR {women labour force participation} OR {womens' employment} OR {female employment} OR {women's unemployment} OR {female unemployment} OR ( access AND {family planning services} ) OR {forced marriage} OR {child marriage} OR {forced marriages} OR {child marriages} OR {occupational segregation} OR {women's empowerment} OR {girls' empowerment} OR {female empowerment} OR {female genital mutilation} OR {female genital cutting} OR {domestic violence} OR {women AND violence} OR {girl* AND violence} OR {sexual violence} OR ( {unpaid work} AND {gender inequality} ) OR ( {unpaid care work} AND {gender inequality} ) OR {women's political participation} OR {female political participation} OR {female managers} OR {women in leadership} OR {female leadership} OR {intra-household allocation} OR ( access AND {reproductive healthcare} ) OR {honour killing} OR {honor killing} OR {honour killings} OR {honor killings} OR {antiwomen} OR {anti-women} OR {feminism} OR {misogyny} OR {female infanticide} OR {female infanticides} OR {human trafficking} OR {forced prostitution} OR ( equality AND ( {sexual rights} OR {reproductive rights} OR {divorce rights} ) ) OR {women's rights} OR {gender injustice} OR {gender injustices} OR {gender discrimination} OR {gender disparities} OR {gender gap} OR {female exploitation} OR {household equity} OR {female political participation} OR {women's underrepresentation} OR {female entrepreneurship} OR {female ownership} OR {women's economic development} OR {women's power} OR {gender-responsive budgeting} OR {gender quota} OR ( {foreign aid} AND {women's empowerment} ) OR {gender segregation} OR {gender-based violence} OR {gender participation} OR {female politician} OR {female leader} OR {contraceptive behaviour} OR {women's autonomy} OR {agrarian feminism} OR {microfinance} OR {women's livelihood} OR {women's ownership} OR {female smallholder} OR {gender mainstreaming} ) )",

        'economic' => "TITLE-ABS-KEY ( ( {economic growth} OR {economic development policy} OR {employment policy} OR {inclusive economic growth} OR {sustainable growth} OR {economic development} OR {economic globalization} OR {economic globalisation} OR {economic productivity} OR {low-carbon economy} OR {inclusive growth} OR microfinanc* OR micro-financ* OR micro-credit* OR microcredit* OR {equal income} OR {equal wages} OR {decent job} OR {decent jobs} OR {quality job} OR {quality jobs} OR {job creation} OR {full employment} OR {employment protection} OR {informal employment} OR {precarious employment} OR {unemployment} OR {precarious job} OR {precarious jobs} OR microenterprise* OR micro-enterprise* OR {small enterprise} OR {medium enterprise} OR {small enterprises} OR {medium enterprises} OR {small entrepreneur} OR {starting entrepreneur} OR {medium entrepreneur} OR {small entrepreneurs} OR {medium entrepreneurs} OR {starting entrepreneurs} OR {social entrepreneurship} OR {safe working environment} OR {labor market institution} OR {labor market institutions} OR {labour market institution} OR {labour market institutions} OR {forced labour} OR {forced labor} OR {child labour} OR {child labor} OR {labour right} OR {labor right} OR {labour rights} OR {labor rights} OR {modern slavery} OR {human trafficking} OR {child soldier} OR {child soldiers} OR {global jobs} OR {living wage} OR {minimum wage} OR {circular economy} OR {inclusive economy} OR {rural economy} OR {Foreign Development Investment} OR {Aid for Trade} OR {trade unions} OR {trade union} OR {working poor} OR {Not in Education, Employment, or Training} OR {carbon offset} OR {carbon offsetting} OR {carbon offsets} OR {offset project} OR {offset projects} OR {economic diversification} OR {material footprint} OR {resource efficiency} OR ( {cradle to cradle} AND {economy} ) OR {economic decoupling} OR {labour market disparities} OR {sustainable tourism} OR {ecotourism} OR {community-based tourism} OR {tourism employment} OR {sustainable tourism policy} OR {financial access} OR {financial inclusion} OR {access to banking} ) AND NOT {health} )",

        'no_poverty' => "TITLE-ABS-KEY ( ( {extreme poverty}  OR  {poverty alleviation}  OR  {poverty eradication}  OR  {poverty reduction}  OR  {international poverty line}  OR  ( {financial aid}  AND  {poverty} )  OR  ( {financial aid}  AND  {poor} )  OR  ( {financial aid}  AND  {north-south divide} )  OR  ( {financial development}  AND  {poverty} )  OR  {financial empowerment}  OR  {distributional effect}  OR  {distributional effects}  OR  {child labor}  OR  {child labour}  OR  {development aid}  OR  {social protection}  OR  {social protection system}  OR  ( {social protection}  AND  access )  OR  microfinanc*  OR  micro-financ*  OR  {resilience of the poor}  OR  ( {safety net}  AND  {poor}  OR  {vulnerable} )  OR  ( {economic resource}  AND  access )  OR  ( {economic resources}  AND  access )  OR  {food bank}  OR  {food banks} ) )",

        'justice' => "TITLE-ABS-KEY ( ( {actual innocence} OR {false confession} OR {armed conflict} OR {armed conflicts} OR {civil conflict} OR {civil conflicts} OR ( war AND ( conflict OR warfare OR democracy OR {Geneva Convention} OR treaty OR peace ) ) OR {peacekeeping} OR ( corruption AND ( {institution} OR {public official} OR {government} OR {bribery} OR {conflict} ) ) OR crime OR crimes OR criminal OR {democratic deficit} OR ( democrati?ation AND ( institutional OR conflict OR decision-making OR society OR politics OR {financial aid} ) ) OR {ethnic conflict} OR {ethnic conflicts} OR exoneration OR genocid* OR homicid* OR murder* OR {human trafficking} OR {criminal justice system} OR {justice system} OR {arbitrary justice} OR refugee* OR terroris* OR violence OR torture OR {effective rule of law} OR {arms flow} OR {transparent institution} OR {transparent institutions} OR {good governance} OR {legal identity for all} OR {freedom of information} OR {human rights institution} OR {human rights activists} OR {fundamental freedom} OR {fundamental freedoms} OR {violent conflict} OR {violent conflicts} OR {peaceful society} OR {effective institution} OR {effective institutions} OR {accountable institution} OR {accountable institutions} OR {inclusive institution} OR {inclusive institutions} OR {child abuse} OR {arbitrary detention} OR {unsentenced detention} OR {judicial system} OR {criminal tribunal} OR {inclusive society} OR {inclusive societies} OR {responsive institution} OR {responsive institutions} OR {fair society} OR {fair societies} OR {legal remedy} OR {legal remedies} OR {independence of judiciary} OR {independent judiciary} OR {separation of powers} OR extremism OR {war crime} OR {peaceful society} OR {organized crime} OR {illicit transfer} OR {illicit money} OR {arms trafficking} OR {cybercrime} OR {insurgence} OR {democratic institution} OR {political instability} OR ( {political decision-making} AND ( responsive OR inclusive OR participatory OR representative ) ) OR {Aarhus Convention} OR {press freedom} OR {freedom of speech} ) AND NOT ( {disease} OR {genetics} ) )",

        "inequality" => "TITLE-ABS-KEY ( ( ( equality  AND  ( economic  OR  financial  OR  socio-economic ) )  OR  ( inequality  AND  ( economic  OR  financial  OR  socio-economic ) )  OR  {economic reform policy}  OR  {economic reform policies}  OR  {political inclusion}  OR  {social protection policy}  OR  {social protection policies}  OR  ( immigration  AND NOT  ( chemistry  OR  disease  OR  biodiversity ) )  OR  ( emigration  AND NOT  ( chemistry  OR  disease  OR  biodiversity ) )  OR  {foreign direct investment}  OR  {development gap}  OR  {development gaps}  OR  {migrant remittance}  OR  {responsible migration}  OR  {migration policy}  OR  {migration policies}  OR  {north-south divide}  OR  ( developing  AND  ( {tariffs}  OR  {tariff}  OR  {zero-tariff}  OR  {duty-free access} ) )  OR  {social exclusion}  OR  {economic marginali?ation}  OR  {income inequality}  OR  {discriminatory law*}  OR  {discriminatory policies}  OR  {discriminatory policy}  OR  {economic empowerment}  OR  {economic transformation}  OR  ( {global market}  AND  {empowerment} ) ) )"
    ];

    public function __construct() {
        $this->client = new Client([
            'base_uri' => 'https://api.elsevier.com/content/search/scopus',
            'headers' => [
                'X-ELS-APIKey' => env('ELSEVIER_API_KEY')
            ]
        ]);
    }

    /**
     * Returns Guzzle Http Client
     *
     * @return Client
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Get pregenerated query
     *
     * @param string $key
     * @return string
     */
    public function getQuery($key)
    {
        if (key_exists($key, $this->queries)) {
            return $this->queries[$key];
        }

        return "";
    }
}
